spring:
  datasource:
    url: jdbc:mysql://localhost:3306/map?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sonamu0928*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate.SQL: debug